social_site/groups/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(),name='all'),
    path('new/', views.CreateGroup.as_view(),name='create'),
    url(r'^posts/in/(?P<slug>[-\w]+)/$', views.SingleGroup.as_view(),name='single'),
    url(r'^join/(?P<slug>[-\w]+)/$', views.JoinGroup.as_view(),name='join'),
    url(r'^leave/(?P<slug>[-\w]+)/$', views.LeaveGroup.as_view(),name='leave'),
]

social_site/posts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    url(r'^by/(?P<username>[-\w]+)/$', views.UserPost.as_view(), name='for_user'),
    # url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='single'),
    url(r'^delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete'),
    url(r'^edit/(?P<pk>\d+)/$', views.EditPost.as_view(), name='edit'),
    url(r'^comment/(?P<pk>\d+)/$', views.CreateComment.as_view(), name='create_comment'),
    url(r'^comment/delete/(?P<pk>\d+)/$', views.DeleteComment.as_view(), name='delete_comment'),
    url(r'^test/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.post_detail, name='single'),
]

social_site/social_site/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from posts import views as post_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', post_view.PostList.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls' , namespace='groups')),
]

social_site/groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

import misaka

from django.contrib.auth import get_user_model

User = get_user_model()

from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=256, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

social_site/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.urls import reverse
from django.contrib import messages
from django.views import generic
from django.shortcuts import get_object_or_404

from .models import Group, GroupMember
from . import models
# Create your views here.

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except InterruptedError:
            messages.warning(self.request, 'Warning already a member')
        else:
            messages.success(self.request, 'You are now member')

        return super().get(self, request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug = self.kwargs.get('slug')
            ).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request, 'SOrry, yo are not in this group')
        else:
            membership.delete()
            messages.success(self.request, 'You have successfully leave the group')
        return super().get(self, request, *args, **kwargs)

social_site/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}

  <div class="container">
    <div class="row">
      {% block pregroup %}{% endblock  %}
      {% block group_content %}{% endblock  %}
      {% block postgroup %}{% endblock  %}
    </div>
  </div>
  
{% endblock  %}

social_site/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}
{% block pregroup %}

  <div class="container">
    <h1>{{ group.name }}</h1>
    <h2>Member count: {{ group.members.count }}</h2>
  </div>
  <div class="container list-group-item">
    <h3>About this group</h3>
    <p> <strong class="list-group-item">{{ group.description }}</strong></p>
  </div>


  <div class="content container">
    {% if user in group.members.all %}
      <a class="btn btn-lg btn-warning" href="{% url 'groups:leave' slug=group.slug %}">Leave</a>
    {% else %}
    <a class="btn btn-lg btn-warning" href="{% url 'groups:join' slug=group.slug %}">Join</a>
    {% endif %}
  </div>

{% endblock  %}

{% block group_content %}

  <div class="col-md-8">
    {% if group.posts.count == 0 %}
      <h2>No posts in this group yet</h2>
    {% else %}
     {% for post in group.posts.all %}
       {% include "posts/_post.html" %}
     {% endfor %}
    {% endif %}
  </div>

  <div class="container-fluid col-md-4">
    <h4>Group Members</h4>
    <div class="jumbotron">
      {% for member in group.memberships.all %}
        <p> <a href="{% url 'posts:for_user' username=member %}">@{{ member }}</a> </p>
      {% endfor %}
    </div>
  </div>

{% endblock  %}

social_site/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}

  <h4>Create a new group</h4>
  <div class="container">
    <form action="{% url 'groups:create' %}" method="post" id='groupForm'>
      {% csrf_token %}
      {% bootstrap_form form %}
      <input class="btn btn-primary btn-lg" type="submit" value="Create">
    </form>
  </div>


{% endblock  %}

social_site/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}

  <div class="col-md-4">
    <div class="content">
      {% if user.is_authenticated %}
        <h2>Welcome back
          <a href="{% url 'posts:for_user' username=user.username %}">
            @{{ user.username }}
          </a>
        </h2>
      {% endif %}
      <h2>Groups</h2>
      <p>Welcome to the group page</p>
    </div>
    {% if user.is_authenticated %}
      <a class="btn btn-md btn-fill btn-warning" href="{% url 'groups:create' %}">New Group</a>
    {% endif %}
  </div>

{% endblock  %}

{% block group_content %}

  <div class="col-md-8">
    <div class="list-group">
      {% for group in object_list %}
        <a class='list-group-item' href="{% url 'groups:single' slug=group.slug %}" id='not_underline'>
          <h3 class="title list-group-item-heading">{{ group.name }}</h3>
          <div class="list-group-item container-fluid">
            {{ group.description_html|safe}}
            <div class="row">
              <div class="col-md-4">
                <span class='badge'>{{ group.members.count }}</span>
                member{{ group.members.count|pluralize }}
              </div>
              <div class="col-md-4">
                <span class="badge">{{ group.posts.count }}</span>
                post{{ group.posts.count|pluralize }}
              </div>
            </div>
          </div>
        </a>
      {% endfor %}
    </div>
  </div>

{% endblock  %}