social_site/posts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    url(r'^by/(?P<username>[-\w]+)/$', views.UserPost.as_view(), name='for_user'),
    # url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='single'),
    url(r'^delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete'),
    url(r'^edit/(?P<pk>\d+)/$', views.EditPost.as_view(), name='edit'),
    url(r'^comment/(?P<pk>\d+)/$', views.CreateComment.as_view(), name='create_comment'),
    url(r'^comment/delete/(?P<pk>\d+)/$', views.DeleteComment.as_view(), name='delete_comment'),
    url(r'^test/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.post_detail, name='single'),
]

social_site/social_site/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from posts import views as post_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', post_view.PostList.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls' , namespace='groups')),
]

social_site/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

import misaka

from groups.models import Group

# Create your models here.

from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username': self.user.username,
                                                'pk': self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']



class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username': self.post.user.username,
                                                'pk': self.post.pk})

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-created_at']

social_site/posts/forms.py
from django import forms
from .models import Post, Comment
from groups.models import Group

class PostForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['group'].queryset = Group.objects.all().filter(members=self.request.user)

    class Meta():
        fields = ('message', 'group')
        model = Post

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

social_site/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.views import generic
from django.http import Http404
from django.contrib import messages

from braces.views import SelectRelatedMixin

from . import models
from . import forms
from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.
class PostList(LoginRequiredMixin, SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(group__members=self.request.user)


        # try:
        #     self.posts_to_show = Group.objects.prefetch_related('posts').get(members=self.request.user)
        # except User.DoesNotExist:
        #     raise Http404
        # else:
        #     return self.posts_to_show.posts.all()


class UserPost(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


def post_detail(request, username, pk):
    post = get_object_or_404(models.Post, pk=pk)
    new_comment = None

    if request.method == 'POST':
        if request.user.id == None:
            raise Http404
        else:
            comment_form = forms.CommentForm(data=request.POST)
            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.post = post
                new_comment.author = request.user
                new_comment.save()
                return redirect('posts:single', pk=post.pk, username=post.user.username)
    else:
        comment_form = forms.CommentForm()
    return render(request, 'posts/post_detail.html', {'post': post, 'form':comment_form})


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    # fields = ('message', 'group')
    model = models.Post
    form_class = forms.PostForm

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(CreatePost, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

class EditPost(LoginRequiredMixin, SelectRelatedMixin, generic.UpdateView):
    model = models.Post
    select_related = ('user', 'group')
    fields = ('message',)

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.user != self.request.user:
            raise Http404
        return super(EditPost, self).dispatch(request, *args, **kwargs)



class CreateComment(LoginRequiredMixin, generic.CreateView):
    model = models.Comment
    fields = ('text', )

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        post_ln = get_object_or_404(models.Post, pk = self.kwargs.get('pk'))
        self.object.post = post_ln
        self.object.save()
        return super().form_valid(form)


class DeleteComment(LoginRequiredMixin, generic.DeleteView):
    model = models.Comment

    def get_success_url(self):
        post = self.object.post
        return reverse_lazy('posts:single', kwargs={'username': post.user.username, 'pk':post.pk})

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(author=self.request.user)
# END

social_site/posts/templates/posts/_post.html
<div class="list-group-item">
  <h5 class="media-heading">
    <span class='username title list-group-item-heading'>
      <a href="{% url 'posts:for_user' username=post.user.username %}">
        @<strong>{{ post.user.username }}</strong>
      </a>
    </span>

    <time class="time">
      <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">
        {{ post.created_at }}
      </a>
      <p>Posted At:
        <a href="{% url 'groups:single' slug=post.group.slug %}">
          {{ post.group }}
        </a>
      </p>
    </time>
  </h5>
  <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}" id='not_underline'>
    <h5 class="list-group-item container-fluid">{{ post.message_html|safe|truncatewords:70 }}
    {% if post.message_html|length != post.message_html|truncatewords:70|length|add:1 %}
      <strong>See more ...</strong>
    {% endif %}
    </h5>
  </a>
  <div class="media-body">


    <div class="media-footer col-md-12">
      {% if user.is_authenticated and not hide %}
        {% if post.user == user %}
          <a class="btn btn-danger" href="{% url 'posts:delete' pk=post.pk %}" title="delete">Delete</a>
          <a class="btn btn-secondary" href="{% url 'posts:edit' pk=post.pk %}" title="edit">Edit Post</a>
        {% endif %}
        {% comment %} <a class="btn btn-primary float-right" href="{% url 'posts:create_comment' pk=post.pk %}">Add Comment</a> {% endcomment %}
        <div class="float-right">
          <h4>
            {% if post.comments.count == 0 %}
              No comments yet
            {% else %}
            {{ post.comments.count }} Comment{{ post.comments.count|pluralize }}
            {% endif %}
          </h4>
        </div>
      {% endif %}
    </div>
  </div>
</div>

social_site/posts/templates/posts/comment_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}

  <h3>Are you sure you want to delete this comment?</h3>
  <div class="container">
    <form method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="Confirm Delete">
    </form>
  </div>

{% endblock  %}

social_site/posts/templates/posts/comment_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap3 %}

{% block post_content %}

  <h4>Comment</h4>
  <div class="container">
    <form id="commentform-id" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input class="btn btn-primary btn-lg" type="submit" value="Comment">
    </form>
  </div>

{% endblock  %}

social_site/posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
  <div class="posts-page">
    <div class="container">
      <div class="row">
        {% block prepost %}{% endblock  %}
        {% block post_content %}{% endblock  %}
        {% block post_post %}{% endblock  %}
      </div>
    </div>
  </div>

{% endblock  %}

social_site/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}

  <h3>Are you sure you want to delete this post?</h3>
  <div class="container">
    <form method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="Confirm Delete">
      <a class="btn btn-primary" href="{% url 'posts:single' username=user.username pk=object.pk %}">Cancel</a>
    </form>
  </div>

  <div class="posts container">
    {% include "posts/_post.html" with post=object hide=True %}
  </div>

{% endblock  %}

social_site/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}
{% load bootstrap3 %}

{% block post_content %}

  <div class="col-md-12">
    <div class="list-group-item">
      <h5 class="media-heading">
        <span class='username title list-group-item'>
          <a href="{% url 'posts:for_user' username=post.user.username %}">
            @<strong>{{ post.user.username }}</strong>
          </a>
        </span>

        <time class="time">
          <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">
            {{ post.created_at }}
          </a>
          <p>Posted At:
            <a href="{% url 'groups:single' slug=post.group.slug %}">
              {{ post.group }}
            </a>
          </p>
        </time>
      </h5>
      <h5 class="list-group-item container-fluid">{{ post.message_html|safe }}</h5>

      <div class="media-body">
        <div class="media-footer">
          {% if user.is_authenticated and post.user == user and not hide %}
            <a class="btn btn-danger" href="{% url 'posts:delete' pk=post.pk %}" title="delete">Delete</a>
            <a class="btn btn-secondary" href="{% url 'posts:edit' pk=post.pk %}" title="edit">Edit Post</a>
          {% endif %}
        </div>
      </div>
    </div>

    <div class="list-group-item">
      <div class="comment">
        {% if post.comments.count == 0 %}
          <h3>No comments yet</h3>
        {% else %}
        <h4>Comments</h4>
        {% for comment in post.comments.all %}
          <div class="comment-header list-group-item">
            <a href="{% url 'posts:for_user' username=comment.author.username %}">
              <p>@<strong>{{ comment.author }}</strong></p>
            </a>
            <div class="comment-date">
              <i>{{ comment.created_at }}</i>
            </div>
            <div class="comment-text">
              <p> <strong> <i>{{ comment.text }}</i> </strong> </p>
            </div>
            {% if user.is_authenticated and comment.author == user %}
              <div class="delete">
                <a class="btn btn-danger" href="{% url 'posts:delete_comment' pk=comment.pk %}" title="delete">Delete</a>
              </div>
            {% endif %}
          </div>
        {% endfor %}
        {% endif %}

        {% if user.is_authenticated %}
          <div class="comment-post">
            <h2>Write a comment</h2>
            <form method="post">
              {% csrf_token %}
              {% bootstrap_form form %}
              <input class='btn btn-primary' type="submit" name="" value="Comment">
            </form>
          </div>
        {% endif %}
      </div>
    </div>
  </div>

{% endblock  %}

social_site/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap3 %}

{% block post_content %}

  <h4>Create a new post</h4>
  <div class="container">
    <form id="postform-id" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input class="btn btn-primary btn-lg" type="submit" value="Post">
    </form>
  </div>

{% endblock  %}

social_site/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}

  <div class="col-md-4">
      {% if request.user.is_authenticated %}
        <div class="card card-with-shadow">
          <div class="content">
            <h5 class="title">Your Groups</h5>
            <ul class="list-unstyle">
              {% if user.user_groups.count == 0 %}
                <p>You are not in any groups</p>
              {% else %}
                {% for member_group in user.user_groups.all %}
                  <li class="group li-with-bullet">
                    <a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group }}</a>
                  </li>
                {% endfor %}
              {% endif %}
            </ul>
          </div>
        </div>
      {% endif %}
      <div class="card card-with-shadow">
        <div class="content">
          <h5 class="title"> <a href="{% url 'groups:all' %}">All Groups</a></h5>
          <ul class="list-unstyled">
            {% for other_group in get_other_groups %}
              <li class="group li-with-bullet">
                <a href="{% url 'groups:single' slug=other_group.slug %}"></a>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
  </div>

{% endblock  %}


{% block post_content %}

  <div class="col-md-8 row">
    {% for post in post_list %}
      {% include "posts/_post.html" %}
    {% endfor %}
  </div>

{% endblock  %}

social_site/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}

  <div class="col-md-4">
    <h1>@{{ post_user.username }}</h1>
  </div>

{% endblock  %}

{% block post_content %}

  <div class="col-md-8">
    {% for post in post_list %}
      {% include "posts/_post.html" %}
      <hr>
    {% endfor %}
  </div>

{% endblock  %}